# Generated by Django 3.2.8 on 2022-05-13 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('limite_minimo', models.IntegerField()),
                ('limite_maximo', models.IntegerField()),
                ('tiempo_medida', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hogar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('potencia_contratada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('intensidad', models.FloatField()),
                ('voltaje', models.FloatField()),
                ('kw', models.FloatField()),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dispositivo', to='api.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hogarInvitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hogarInvitado', to='api.hogar')),
                ('invitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitado', to='api.usuario')),
                ('invitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitante', to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='hogar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='hogar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hogar', to='api.hogar'),
        ),
        migrations.CreateModel(
            name='Compartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartido', to='api.usuario')),
                ('hogarCompartido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hogarCompartido', to='api.hogar')),
            ],
        ),
    ]
