# Generated by Django 3.2.8 on 2022-09-03 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('verificado', models.BooleanField()),
                ('notificacion', models.BooleanField()),
                ('general', models.BooleanField()),
                ('limite_minimo', models.FloatField()),
                ('limite_maximo', models.FloatField()),
                ('tiempo_medida', models.IntegerField()),
                ('tiempo_refrescado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hogar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('potencia_contratada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('notificacion_invitados', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('intensidad', models.FloatField()),
                ('voltaje', models.FloatField()),
                ('kw', models.FloatField()),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dispositivo', to='api.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hogarInvitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hogarInvitado', to='api.hogar')),
                ('invitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitado', to='api.usuario')),
                ('invitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitante', to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='hogar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='api.usuario'),
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDia', models.DateTimeField()),
                ('sumaDiaKw', models.FloatField()),
                ('sumaDiaDinero', models.FloatField()),
                ('fechaMes', models.DateTimeField()),
                ('sumaMesKw', models.FloatField()),
                ('sumaMesDinero', models.FloatField()),
                ('sumaTotalKw', models.FloatField()),
                ('sumaTotalDinero', models.FloatField()),
                ('numDiasTotal', models.IntegerField()),
                ('numMesTotal', models.IntegerField()),
                ('minDiaKw', models.FloatField()),
                ('fechaMinDiaKw', models.DateField()),
                ('maxDiaKw', models.FloatField()),
                ('fechaMaxDiaKw', models.DateField()),
                ('minMesKw', models.FloatField()),
                ('fechaMinMesKw', models.DateField()),
                ('maxMesKw', models.FloatField()),
                ('fechaMaxMesKw', models.DateField()),
                ('fechaSemana', models.DateTimeField()),
                ('sumaSemanaKw', models.FloatField()),
                ('fechaAño', models.DateTimeField()),
                ('sumaAñoKw', models.FloatField()),
                ('tramosHoras', models.JSONField()),
                ('tramoSemanal', models.JSONField()),
                ('tramosMensual', models.JSONField()),
                ('historicoDiario', models.JSONField()),
                ('historicoMensual', models.JSONField()),
                ('historicoMasConsumido', models.JSONField()),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivo_estadisitica_diaria', to='api.dispositivo')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='hogar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hogar', to='api.hogar'),
        ),
        migrations.CreateModel(
            name='Compartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartido', to='api.usuario')),
                ('hogarCompartido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hogarCompartido', to='api.hogar')),
            ],
        ),
    ]
