# Generated by Django 3.2.8 on 2022-06-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadistica',
            name='maxDiaDinero',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='estadistica',
            name='maxMesDinero',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='estadistica',
            name='minDiaDinero',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='estadistica',
            name='minMesDinero',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='estadistica',
            name='sumaDiaDinero',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='estadistica',
            name='sumaMesDinero',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='estadistica',
            name='sumaTotalDinero',
            field=models.FloatField(default=0.0),
        ),
    ]
