# Generated by Django 3.2.8 on 2022-06-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220611_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadistica',
            name='maxDiaDinero',
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='maxMesDinero',
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='minDiaDinero',
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='minMesDinero',
        ),
    ]
